### ISSUE TITLE
Partner Logo W/E is missing and gives an error

### ISSUE THREAD

**Issue by sbosman84** [Madaster/feedback#10]
**Describe the bug**
Partner Logo W/E is missing and gives an error

**To Reproduce**
1. Navigate to https://platform.madaster.com/building/cefdd33a-b484-4ff4-9d72-12350ea8e73c/apps
2. Check the console log

**Expected behavior**
See logo's :-)

**Screenshots**
![image](https://user-images.githubusercontent.com/15688831/114931027-f7a25b80-9e35-11eb-923b-2e3cfe239aed.png)

**Comment by mlankamp** [comment]
Fixed!
