### ISSUE TITLE
Bug Deleting picture 

### ISSUE THREAD

**Issue by claudiusfrank** [Madaster/feedback#12]
**Describe the bug**
Picture is deleted, but will not get removed

**To Reproduce**
1. Go to Building https://platform.madaster.com/building/df45d6fd-4b70-48ce-b5a3-2f43735602f3/
2. Click on 'Edit'
3. 'Delete Building'
4. Picture will not get removed

**Expected behavior**
Deleted Picture

**Comment by mlankamp** [comment]
The bug is solved on 26 january 2022
