### ISSUE TITLE
Passport Bug

### ISSUE THREAD

**Issue by claudiusfrank** [Madaster/feedback#13]
**Circularity in Passport shown wrong** 
**To Reproduce**
1. Go to 'Building https://platform.madaster.com/building/b6a2e58e-b78b-4fec-981e-a4dab6d4c475/files'
2. Click on 'Create Passport'
3. Open Passport in Dossier '....'
4. See error on page 30/31
5. 
![image](https://user-images.githubusercontent.com/73991582/150360797-cab7a0ca-d886-4f54-9770-d4697e073a9e.png)

**Comment by mlankamp** [comment]
Fixed in the next release
