### ISSUE TITLE
Consider better mapping solution

### ISSUE THREAD

**Issue by AnsteinS** [Madaster/feedback#16]
**Please describe.**
 The mapping solution in Building – General should be considered. Is it accurate in all countries, and can we find a solution with better functionality (eg. Pin location, partial writing of address, reduce misspelling etc.)? 

**Wrong result in currrent map solution:**
https://platform.madaster.com/building/f19b6565-4fe9-43d7-af78-b0299883dcc9/ 
<img width="685" alt="image" src="https://user-images.githubusercontent.com/74861081/156142606-de4c14ee-c21c-45e0-855d-fc55ae33ab68.png">

**Example of partial input and suggested results i Google Maps:**
<img width="628" alt="image" src="https://user-images.githubusercontent.com/74861081/156143074-78bdcb75-c8e6-46e9-a1f1-14487ec8c06c.png">

**Comment by mlankamp** [comment]
Solved
