### ISSUE TITLE
Translation keys don't work

### ISSUE THREAD

**Issue by Vinver80** [Madaster/feedback#20]
**Describe the bug**
When I choose for the 'Vertalingssleutels' on the accept platform I see the keys. If I click on something the keys disappear again and I'm back in my original language.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mlankamp** [comment]
Solved
