### ISSUE TITLE
Error 404 Docs

### ISSUE THREAD

**Issue by claudiusfrank** [Madaster/feedback#21]
**Describe the bug**
Error 404 when clicking on the i. 

**To Reproduce**
1. Go to '[.](https://platform.madaster.com/building/eb038a71-fe8d-4266-af66-87ec1c7c61fb/files/75acde7a-a64c-4bc3-a23f-c042df64c05a/)'
2. Click on 'information'
4. See error 404

**Expected behavior**

**Screenshots**
![2022-05-03 10_12_56-Page not found · GitHub Pages](https://user-images.githubusercontent.com/73991582/166422662-b46fb03c-1a12-4a8d-9a9f-7dd10a0fecc3.png)

**Comment by mlankamp** [comment]
There was a small configuration error, updated the confirguation.
