### ISSUE TITLE
Deleting search criteria in EPEA-database customer

### ISSUE THREAD

**Issue by Vinver80** [Madaster/feedback#23]
Apparently I have the rights to add search criteria in the EPEA-database of the customer. But, I can't delete in it. At first sight I have deleted it but if I check afterwards it is not deleted.
https://platform.madaster.com/database/00000000-0000-0000-0000-000000000001/accountadmin/074c05f9-7932-ec11-b6e6-000d3abaa200/product/view/f2159869-8dac-4ca6-8eeb-35d135541547/searchcriteria 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mlankamp** [comment]
Fix is created and deployed
