### ISSUE TITLE
Madaster tilbakemelding

### ISSUE THREAD

**Issue by marikveinesweco** [Madaster/feedback#28]
![image](https://user-images.githubusercontent.com/108003625/177311569-77d0ab59-cf2c-44f5-8e87-8302a8631d5d.png)

Det burde stå i feilmelding hva slags filtyper som er tilltatt, dessuten er jeg usikker på hvorfor jeg får feilmelding når det er en revit-fil

**Comment by mlankamp** [comment]
We have added a help text to describe which files types we support
