### ISSUE TITLE
In editing a material, marking the box an clicking on the pencil

### ISSUE THREAD

**Issue by marikveinesweco** [Madaster/feedback#29]
**Describe the bug**

**To Reproduce**
1. Go to "berike modell" (dont know the english word, google translate suggested reach". 
2. Click on a material and mark the box
3. Click on the pencil on the tool bar that is shown
4. click on classification, and look at the option
**Expected behavior**
The only option when clicking classification is "leave unchanged", no option that can help is available

**Screenshots**
![image](https://user-images.githubusercontent.com/108003625/177490854-58a6af4f-58a8-4c86-b7eb-497ae7c6c5ae.png)

**Desktop (please complete the following information):**
 - Windows
 - Edge

**Additional context**

**Comment by mlankamp** [comment]
@stephanieguyot I've looked at the problem, and I think this related to the `NS 3451` classifcation. Since we aren't allowed to show the contents of this classifcation. The solution would be to hide the dropdown in case of `NS 3451`.

**Comment by mlankamp** [comment]
Because of strick restriction on the usage of `NS 3451` we have decided the list is hidden to prevent this problem.
