### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by Mariameland** [Madaster/feedback#30]
Hi,

Is there any reason why dimensions do not export with IFC-files into Madaster? In other words, when a building is imported as an IFC-file into Madaster, and the components have given dimensions, why aren't the dimensons being imported as well? Is there any setting in Revit that makes it possible to get the dimensions imported to Madaster?

**Comment by marikveinesweco** [comment]
And is there alternatively an option to let the users manually plot in, because we see that alot of the elements have dimensions in reit but not in madaster.

**Comment by mlankamp** [comment]
On [Madaster documentation](https://docs.madaster.com/no/nb/) you can find 2 manuals about the ifc import/export process. Make sure the basequantities are exported, because these are used by Madaster.
