### ISSUE TITLE
Hi! I wanted to export an english pdf of our material passport but trying to download it, I get an error Notification (https://prodmdstrstorage.blob.core.windows.net/buildings/building-d5bf3140-8d93-44b0-ac8b-b1d4ed71329d/passports/passport_20221012114928.pdf?sv=2021-08-06&se=2022-10-12T12%3A05%3A56Z&sr=b&sp=r&sig=HhghNxQIZI9Ji1uDEK0D5Ladk7MEJGIbwxBaB7w6JGA%3D)

### ISSUE THREAD

**Issue by Franziskaalbrecht** [Madaster/feedback#33]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stephanieguyot** [comment]
Refresh your screen as the download link are only valid for 15 minutes.

**Comment by Franziskaalbrecht** [comment]
Thank you, Stephanie!

Von: stephanieguyot ***@***.***>
Gesendet: Mittwoch, 12. Oktober 2022 14:50
An: madaster/feedback ***@***.***>
Cc: Franziska Albrecht ***@***.***>; Author ***@***.***>
Betreff: Re: [madaster/feedback] Hi! I wanted to export an english pdf of our material passport but trying to download it, I get an error Notification (https://prodmdstrstorage.blob.core.windows.net/buildings/building-d5bf3140-8d93-44b0-ac8b-b1d4ed71329d/passpo...


Refresh your screen as the download link are only valid for 15 minutes.
