### ISSUE TITLE
Database toevoegen aan gebouw

### ISSUE THREAD

**Issue by jkoomen** [Madaster/feedback#4]
Ik merk dat als ik database toevoeg op gebouw niveau... ik deze opeens niet meer terugzie in de balk links...
Als ik dan uitlog en inlog zie ik hem weer wel... 

Daardoor heb ik er nu per ongeluk 2 aangemaakt... 
Ook kan ik geen knopjes vinden om deze database dan weer weg te gooien.
Hoe kan ik database weer weggooien?

In onderstaand screenshot zie ik ze wel..

![image](https://user-images.githubusercontent.com/72186536/94782228-3b1e0680-03cb-11eb-8744-d46445d06b17.png)

Als ik dan iets aanpas zie ik database opeens niet meer

![image](https://user-images.githubusercontent.com/72186536/94782486-951ecc00-03cb-11eb-9558-e68deda40669.png)

**Comment by mlankamp** [comment]
De functionaliteit voor het verwijderen van een database staat nog op de backlog en zal zsm online komen.

**Comment by stephanieguyot** [comment]
De functionaliteit voor het verwijderen van database is onderdeeln van de release die uitgerold is op 16-10-2020.
Ook de bug met betrekking tot het niet tonen van de database in de navigatie is opgelost.
